"""Initial

Revision ID: 747d25f63b09
Revises: 
Create Date: 2026-05-07 22:54:31.867738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747d25f63b09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gln', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('datapool', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_gln'), 'companies', ['gln'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_password'), 'companies', ['password'], unique=False)
    op.create_table('registrymessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gln', sa.String(), nullable=True),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrymessages_description'), 'registrymessages', ['description'], unique=False)
    op.create_index(op.f('ix_registrymessages_gln'), 'registrymessages', ['gln'], unique=False)
    op.create_index(op.f('ix_registrymessages_gtin'), 'registrymessages', ['gtin'], unique=False)
    op.create_index(op.f('ix_registrymessages_id'), 'registrymessages', ['id'], unique=False)
    op.create_index(op.f('ix_registrymessages_name'), 'registrymessages', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrymessages_name'), table_name='registrymessages')
    op.drop_index(op.f('ix_registrymessages_id'), table_name='registrymessages')
    op.drop_index(op.f('ix_registrymessages_gtin'), table_name='registrymessages')
    op.drop_index(op.f('ix_registrymessages_gln'), table_name='registrymessages')
    op.drop_index(op.f('ix_registrymessages_description'), table_name='registrymessages')
    op.drop_table('registrymessages')
    op.drop_index(op.f('ix_companies_password'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_gln'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
