"""publication table

Revision ID: 9cf475c5eb2d
Revises: d7646388de68
Create Date: 2026-05-14 21:57:37.142535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf475c5eb2d'
down_revision: Union[str, Sequence[str], None] = 'd7646388de68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtin', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('subscriber', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_gtin'), 'publications', ['gtin'], unique=False)
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_index(op.f('ix_publications_subscriber'), 'publications', ['subscriber'], unique=False)
    op.create_index(op.f('ix_publications_supplier'), 'publications', ['supplier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_supplier'), table_name='publications')
    op.drop_index(op.f('ix_publications_subscriber'), table_name='publications')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_gtin'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
